apiVersion: v1
kind: ReplicationController
metadata:
  name: html-blue
  labels:
    app: html-blue

spec:
  replicas: 1
  selector:
    app: html-blue
  template:
    metadata:
      labels:
        app: html-blue
    spec:
      containers:
      - name: html-blue
        image: ikuku/html-blue
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 80