apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      namespace: jenkins
      serviceAccountName: jenkins
      automountServiceAccountToken: false
      containers:
      - name: simple-laravel
        image: ikuku/simple-laravel:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-entrypoint
spec:
  type: LoadBalancer
  selector:
    app: laravel
  ports:
  - protocol: TCP
    port: 8080