kind: Service
apiVersion: v1
metadata:
  name: blue-green-service
  labels:
    app: blue-green-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: html-green
  type: LoadBalancer