apiVersion: v1
kind: ReplicationController
metadata:
  name: html-green
  labels:
    app: html-green

spec:
  replicas: 1
  selector:
    app: html-green
  template:
    metadata:
      labels:
        app: html-green
    spec:
      containers:
      - name: html-green
        image: ikuku/html-green
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 80