apiVersion: v1
kind: ReplicationController
metadata:
  name: laravel-green
  labels:
    app: laravel-green

spec:
  replicas: 1
  selector:
    app: laravel-green
  template:
    metadata:
      labels:
        app: laravel-green
    specs:
      containers:
        name: laravel-green
        image: ikuku/laravel-green
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 80